#!/usr/bin/env python
import sys
import util
import os
import constants


def process_files(file_path1, file_path2, n_files):
    """
    Arguments: filepath x filepath 
    
    Identifies and returns matches between two different files.
    
    This method prints:
        'MATCH ' followed by the resource files of the given 
        file paths if the resource files warrant a match.
        
        OR
        
        'NO MATCH' if the resource files of the given file paths 
        do not match.
    """
    file_name1 = util.get_file_name(file_path1)
    file_name2 = util.get_file_name(file_path2)  
    if (util.is_supported_file(file_path1) 
    and util.is_supported_file(file_path2)):
        util.compare(file_path1, file_path2, n_files)

def main(argv):
    """
    Arguments: argv (stdin)

    Main method that executes our Audio File Comparison Application.
    """

    # Check to see if the given arguments are valid.
    util.check_args(argv)
    
    # Conditions to process and identify matching files.

    # If the input contains two files:
    if argv[1] == '-f' and argv[3] == '-f':
        process_files(argv[2], argv[4], 1)
    # If the input contains a file and a directory:
    elif argv[1] == '-f' and argv[3] == '-d':
        files = util.get_files(argv[4])
        for file in files:
            file_path = util.get_file_path(file, argv[4])
            process_files(argv[2], file_path, len(files))
    # If the input contains a directory and a file:
    elif argv[1] == '-d' and argv[3] == '-f':
        files = util.get_files(argv[2])
        for file in files:
            file_path = util.get_file_path(file, argv[2])
            process_files(file_path, argv[4], len(files))
    # If the input contains two directories:
    elif argv[1] == '-d' and argv[3] == '-d':
        files1 = util.get_files(argv[2])
        files2 = util.get_files(argv[4]) 
        for file1 in files1:
            for file2 in files2:
                file_path1 = util.get_file_path(file1, argv[2])
                file_path2 = util.get_file_path(file2, argv[4])
                process_files(file_path1, file_path2, len(files1))
    util.del_temp_files()

if __name__ == "__main__":
    main(sys.argv)

